# Generated by Django 3.2.5 on 2021-07-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='article_category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='creation_date',
            new_name='article_creation_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='article_name',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='photo',
            new_name='article_photo',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='article_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='comment_article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='tecx',
            new_name='comment_text',
        ),
    ]
