# Generated by Django 3.2.5 on 2021-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210725_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='Text'),
        ),
    ]
