# Generated by Django 3.2.5 on 2021-07-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_comment_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
    ]
