# Generated by Django 3.2.5 on 2021-07-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210726_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=1700, null=True, verbose_name='Text'),
        ),
    ]
