# Generated by Django 3.2.5 on 2021-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tags'),
        ),
    ]
